import { DistrictGapAggregate, GapScoreItem, OversupplyAlert, SeverityLevel } from '../../types/api';

/**
 * Standardized algorithmic gap score formula (0.0 to 100.0)
 * Matching backend GapScoringService.calculate_normalized_gap
 */
export function calculateNormalizedGap(
  demandCount: number,
  trendFactor: number,
  trainedCapacity: number,
  placementRate: number,
  scalingConstant: number = 1000.0
): number {
  const effectiveDemand = demandCount * trendFactor;
  const rateMultiplier = placementRate > 1 ? placementRate / 100.0 : placementRate;
  const effectiveSupply = trainedCapacity * rateMultiplier;
  const rawGap = effectiveDemand - effectiveSupply;
  const normalized = (rawGap / scalingConstant) * 100.0;
  return Number(Math.min(100.0, Math.max(0.0, normalized)).toFixed(2));
}

export function getSeverityLevel(score: number): SeverityLevel {
  if (score >= 75) return 'CRITICAL';
  if (score >= 60) return 'HIGH';
  if (score >= 40) return 'MODERATE';
  return 'LOW';
}

export function isStructurallyOversupplied(
  placementRate: number,
  localDemandPercentile: number,
  consecutiveQuarters: number = 2
): boolean {
  return placementRate < 25.0 && localDemandPercentile < 20 && consecutiveQuarters >= 2;
}

/**
 * 36 Administrative Districts of Maharashtra across 6 Divisions
 */
export const MAHARASHTRA_DISTRICTS: DistrictGapAggregate[] = [
  // 1. Pune Division (5)
  {
    id: 14,
    code: 'PUN',
    name_en: 'Pune',
    name_mr: 'पुणे',
    name_hi: 'पुणे',
    division: 'Pune',
    total_vacancies: 14200,
    total_capacity: 8400,
    average_gap_score: 82.5,
    severity_level: 'CRITICAL',
    critical_trades_count: 5,
    iti_count: 38,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 15,
    code: 'SAT',
    name_en: 'Satara',
    name_mr: 'सातारा',
    name_hi: 'सतारा',
    division: 'Pune',
    total_vacancies: 2100,
    total_capacity: 1950,
    average_gap_score: 48.0,
    severity_level: 'MODERATE',
    critical_trades_count: 1,
    iti_count: 16,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 16,
    code: 'SOL',
    name_en: 'Solapur',
    name_mr: 'सोलापूर',
    name_hi: 'सोलापुर',
    division: 'Pune',
    total_vacancies: 3400,
    total_capacity: 2200,
    average_gap_score: 64.2,
    severity_level: 'HIGH',
    critical_trades_count: 2,
    iti_count: 21,
    has_oversupply_alert: true,
    oversupply_trades_count: 1,
  },
  {
    id: 17,
    code: 'KOL',
    name_en: 'Kolhapur',
    name_mr: 'कोल्हापूर',
    name_hi: 'कोल्हापुर',
    division: 'Pune',
    total_vacancies: 4600,
    total_capacity: 3100,
    average_gap_score: 68.5,
    severity_level: 'HIGH',
    critical_trades_count: 2,
    iti_count: 24,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 18,
    code: 'SNG',
    name_en: 'Sangli',
    name_mr: 'सांगली',
    name_hi: 'सांगली',
    division: 'Pune',
    total_vacancies: 2300,
    total_capacity: 1800,
    average_gap_score: 51.4,
    severity_level: 'MODERATE',
    critical_trades_count: 1,
    iti_count: 17,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },

  // 2. Nashik Division (5)
  {
    id: 20,
    code: 'NSK',
    name_en: 'Nashik',
    name_mr: 'नाशिक',
    name_hi: 'नासिक',
    division: 'Nashik',
    total_vacancies: 6800,
    total_capacity: 4200,
    average_gap_score: 74.0,
    severity_level: 'HIGH',
    critical_trades_count: 3,
    iti_count: 28,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 21,
    code: 'AHM',
    name_en: 'Ahmednagar',
    name_mr: 'अहिल्यानगर',
    name_hi: 'अहमदनगर',
    division: 'Nashik',
    total_vacancies: 3100,
    total_capacity: 2600,
    average_gap_score: 55.0,
    severity_level: 'MODERATE',
    critical_trades_count: 1,
    iti_count: 22,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 22,
    code: 'JAL',
    name_en: 'Jalgaon',
    name_mr: 'जळगाव',
    name_hi: 'जलगांव',
    division: 'Nashik',
    total_vacancies: 2400,
    total_capacity: 2100,
    average_gap_score: 46.5,
    severity_level: 'MODERATE',
    critical_trades_count: 1,
    iti_count: 18,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 23,
    code: 'DHU',
    name_en: 'Dhule',
    name_mr: 'धुळे',
    name_hi: 'धुले',
    division: 'Nashik',
    total_vacancies: 1200,
    total_capacity: 1400,
    average_gap_score: 32.0,
    severity_level: 'LOW',
    critical_trades_count: 0,
    iti_count: 11,
    has_oversupply_alert: true,
    oversupply_trades_count: 1,
  },
  {
    id: 24,
    code: 'NDB',
    name_en: 'Nandurbar',
    name_mr: 'नंदुरबार',
    name_hi: 'नंदुरबार',
    division: 'Nashik',
    total_vacancies: 800,
    total_capacity: 1100,
    average_gap_score: 28.5,
    severity_level: 'LOW',
    critical_trades_count: 0,
    iti_count: 9,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },

  // 3. Konkan Division (7)
  {
    id: 1,
    code: 'MUM',
    name_en: 'Mumbai City',
    name_mr: 'मुंबई शहर',
    name_hi: 'मुंबई शहर',
    division: 'Konkan',
    total_vacancies: 8900,
    total_capacity: 3200,
    average_gap_score: 79.2,
    severity_level: 'CRITICAL',
    critical_trades_count: 4,
    iti_count: 12,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 2,
    code: 'MSU',
    name_en: 'Mumbai Suburban',
    name_mr: 'मुंबई उपनगर',
    name_hi: 'मुंबई उपनगर',
    division: 'Konkan',
    total_vacancies: 11200,
    total_capacity: 4800,
    average_gap_score: 81.0,
    severity_level: 'CRITICAL',
    critical_trades_count: 4,
    iti_count: 18,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 3,
    code: 'THA',
    name_en: 'Thane',
    name_mr: 'ठाणे',
    name_hi: 'ठाणे',
    division: 'Konkan',
    total_vacancies: 7800,
    total_capacity: 4500,
    average_gap_score: 76.5,
    severity_level: 'CRITICAL',
    critical_trades_count: 3,
    iti_count: 24,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 4,
    code: 'PLG',
    name_en: 'Palghar',
    name_mr: 'पालघर',
    name_hi: 'पालघर',
    division: 'Konkan',
    total_vacancies: 3200,
    total_capacity: 1900,
    average_gap_score: 62.1,
    severity_level: 'HIGH',
    critical_trades_count: 1,
    iti_count: 14,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 5,
    code: 'RAI',
    name_en: 'Raigad',
    name_mr: 'रायगड',
    name_hi: 'रायगढ़',
    division: 'Konkan',
    total_vacancies: 4100,
    total_capacity: 2500,
    average_gap_score: 67.8,
    severity_level: 'HIGH',
    critical_trades_count: 2,
    iti_count: 16,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 6,
    code: 'RAT',
    name_en: 'Ratnagiri',
    name_mr: 'रत्नागिरी',
    name_hi: 'रत्नागिरी',
    division: 'Konkan',
    total_vacancies: 1500,
    total_capacity: 1700,
    average_gap_score: 38.0,
    severity_level: 'LOW',
    critical_trades_count: 0,
    iti_count: 13,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 7,
    code: 'SND',
    name_en: 'Sindhudurg',
    name_mr: 'सिंधुदुर्ग',
    name_hi: 'सिंधुदुर्ग',
    division: 'Konkan',
    total_vacancies: 950,
    total_capacity: 1200,
    average_gap_score: 31.2,
    severity_level: 'LOW',
    critical_trades_count: 0,
    iti_count: 10,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },

  // 4. Chhatrapati Sambhajinagar (Marathwada) Division (8)
  {
    id: 25,
    code: 'CSN',
    name_en: 'Chh. Sambhajinagar',
    name_mr: 'छत्रपती संभाजीनगर',
    name_hi: 'छत्रपति संभाजीनगर',
    division: 'Chhatrapati Sambhajinagar',
    total_vacancies: 5600,
    total_capacity: 3400,
    average_gap_score: 75.8,
    severity_level: 'CRITICAL',
    critical_trades_count: 3,
    iti_count: 23,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 26,
    code: 'JLN',
    name_en: 'Jalna',
    name_mr: 'जालना',
    name_hi: 'जालना',
    division: 'Chhatrapati Sambhajinagar',
    total_vacancies: 2200,
    total_capacity: 1600,
    average_gap_score: 58.4,
    severity_level: 'MODERATE',
    critical_trades_count: 1,
    iti_count: 12,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 27,
    code: 'PRB',
    name_en: 'Parbhani',
    name_mr: 'परभणी',
    name_hi: 'परभणी',
    division: 'Chhatrapati Sambhajinagar',
    total_vacancies: 1100,
    total_capacity: 1300,
    average_gap_score: 34.0,
    severity_level: 'LOW',
    critical_trades_count: 0,
    iti_count: 11,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 28,
    code: 'HNG',
    name_en: 'Hingoli',
    name_mr: 'हिंगोली',
    name_hi: 'हिंगोली',
    division: 'Chhatrapati Sambhajinagar',
    total_vacancies: 750,
    total_capacity: 900,
    average_gap_score: 29.0,
    severity_level: 'LOW',
    critical_trades_count: 0,
    iti_count: 7,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 29,
    code: 'NED',
    name_en: 'Nanded',
    name_mr: 'नांदेड',
    name_hi: 'नांदेड़',
    division: 'Chhatrapati Sambhajinagar',
    total_vacancies: 1900,
    total_capacity: 1800,
    average_gap_score: 47.2,
    severity_level: 'MODERATE',
    critical_trades_count: 1,
    iti_count: 15,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 30,
    code: 'BEE',
    name_en: 'Beed',
    name_mr: 'बीड',
    name_hi: 'बीड',
    division: 'Chhatrapati Sambhajinagar',
    total_vacancies: 1350,
    total_capacity: 1550,
    average_gap_score: 36.5,
    severity_level: 'LOW',
    critical_trades_count: 0,
    iti_count: 14,
    has_oversupply_alert: true,
    oversupply_trades_count: 1,
  },
  {
    id: 31,
    code: 'LAT',
    name_en: 'Latur',
    name_mr: 'लातूर',
    name_hi: 'लातूर',
    division: 'Chhatrapati Sambhajinagar',
    total_vacancies: 1850,
    total_capacity: 1650,
    average_gap_score: 49.0,
    severity_level: 'MODERATE',
    critical_trades_count: 1,
    iti_count: 14,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 32,
    code: 'DHA',
    name_en: 'Dharashiv',
    name_mr: 'धाराशिव',
    name_hi: 'धाराशिव',
    division: 'Chhatrapati Sambhajinagar',
    total_vacancies: 1050,
    total_capacity: 1250,
    average_gap_score: 33.5,
    severity_level: 'LOW',
    critical_trades_count: 0,
    iti_count: 10,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },

  // 5. Nagpur Division (6)
  {
    id: 8,
    code: 'NGP',
    name_en: 'Nagpur',
    name_mr: 'नागपूर',
    name_hi: 'नागपुर',
    division: 'Nagpur',
    total_vacancies: 6200,
    total_capacity: 3900,
    average_gap_score: 72.4,
    severity_level: 'HIGH',
    critical_trades_count: 3,
    iti_count: 26,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 9,
    code: 'WRD',
    name_en: 'Wardha',
    name_mr: 'वर्धा',
    name_hi: 'वर्धा',
    division: 'Nagpur',
    total_vacancies: 1450,
    total_capacity: 1350,
    average_gap_score: 44.0,
    severity_level: 'MODERATE',
    critical_trades_count: 0,
    iti_count: 11,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 10,
    code: 'BHA',
    name_en: 'Bhandara',
    name_mr: 'भंडारा',
    name_hi: 'भंडारा',
    division: 'Nagpur',
    total_vacancies: 1150,
    total_capacity: 1200,
    average_gap_score: 37.0,
    severity_level: 'LOW',
    critical_trades_count: 0,
    iti_count: 9,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 11,
    code: 'GON',
    name_en: 'Gondia',
    name_mr: 'गोंदिया',
    name_hi: 'गोंदिया',
    division: 'Nagpur',
    total_vacancies: 850,
    total_capacity: 1050,
    average_gap_score: 30.5,
    severity_level: 'LOW',
    critical_trades_count: 0,
    iti_count: 8,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 12,
    code: 'CHA',
    name_en: 'Chandrapur',
    name_mr: 'चंद्रपूर',
    name_hi: 'चंद्रपुर',
    division: 'Nagpur',
    total_vacancies: 3100,
    total_capacity: 2100,
    average_gap_score: 63.5,
    severity_level: 'HIGH',
    critical_trades_count: 1,
    iti_count: 15,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 13,
    code: 'GAD',
    name_en: 'Gadchiroli',
    name_mr: 'गडचिरोली',
    name_hi: 'गडचिरोली',
    division: 'Nagpur',
    total_vacancies: 700,
    total_capacity: 950,
    average_gap_score: 26.0,
    severity_level: 'LOW',
    critical_trades_count: 0,
    iti_count: 8,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },

  // 6. Amravati Division (5)
  {
    id: 33,
    code: 'AMR',
    name_en: 'Amravati',
    name_mr: 'अमरावती',
    name_hi: 'अमरावती',
    division: 'Amravati',
    total_vacancies: 2900,
    total_capacity: 2200,
    average_gap_score: 59.2,
    severity_level: 'MODERATE',
    critical_trades_count: 1,
    iti_count: 19,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 34,
    code: 'AKO',
    name_en: 'Akola',
    name_mr: 'अकोला',
    name_hi: 'अकोला',
    division: 'Amravati',
    total_vacancies: 1800,
    total_capacity: 1700,
    average_gap_score: 45.0,
    severity_level: 'MODERATE',
    critical_trades_count: 0,
    iti_count: 13,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 35,
    code: 'YAV',
    name_en: 'Yavatmal',
    name_mr: 'यवतमाळ',
    name_hi: 'यवतमाल',
    division: 'Amravati',
    total_vacancies: 1500,
    total_capacity: 1600,
    average_gap_score: 38.5,
    severity_level: 'LOW',
    critical_trades_count: 0,
    iti_count: 14,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 36,
    code: 'BUL',
    name_en: 'Buldhana',
    name_mr: 'बुलढाणा',
    name_hi: 'बुलढाणा',
    division: 'Amravati',
    total_vacancies: 1400,
    total_capacity: 1500,
    average_gap_score: 37.0,
    severity_level: 'LOW',
    critical_trades_count: 0,
    iti_count: 13,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
  {
    id: 37,
    code: 'WAS',
    name_en: 'Washim',
    name_mr: 'वाशिम',
    name_hi: 'वाशिम',
    division: 'Amravati',
    total_vacancies: 650,
    total_capacity: 850,
    average_gap_score: 25.5,
    severity_level: 'LOW',
    critical_trades_count: 0,
    iti_count: 7,
    has_oversupply_alert: false,
    oversupply_trades_count: 0,
  },
];

/**
 * Granular trade-level gap records across key industrial districts
 */
export const MOCK_GAP_SCORES: GapScoreItem[] = [
  {
    id: 'gap-001',
    district_id: 14,
    district_name_en: 'Pune',
    district_name_mr: 'पुणे',
    district_name_hi: 'पुणे',
    sector_id: 1,
    sector_name: 'Automotive & Clean Mobility',
    job_role_title_en: 'EV Powertrain & Battery Diagnostics',
    job_role_title_mr: 'ईव्ही पॉवरट्रेन आणि बॅटरी निदान तंत्रज्ञ',
    job_role_title_hi: 'ईवी पावरट्रेन एवं बैटरी डायग्नोस्टिक्स',
    qp_code: 'ASC/Q1402',
    nsqf_level: 4,
    demand_count: 1850,
    trained_capacity: 480,
    placement_rate: 82.5,
    gap_score: 86.4,
    severity_level: 'CRITICAL',
    trend_direction: 'RISING',
  },
  {
    id: 'gap-002',
    district_id: 14,
    district_name_en: 'Pune',
    district_name_mr: 'पुणे',
    district_name_hi: 'पुणे',
    sector_id: 2,
    sector_name: 'Capital Goods & Precision',
    job_role_title_en: 'CNC Multi-Axis Milling Specialist',
    job_role_title_mr: 'सीएनसी मल्टि-अ‍ॅक्सिस मिलिंग तज्ज्ञ',
    job_role_title_hi: 'सीएनसी मल्टी-एक्सिस मिलिंग विशेषज्ञ',
    qp_code: 'CSC/Q0115',
    nsqf_level: 4,
    demand_count: 1420,
    trained_capacity: 560,
    placement_rate: 78.0,
    gap_score: 81.2,
    severity_level: 'CRITICAL',
    trend_direction: 'RISING',
  },
  {
    id: 'gap-003',
    district_id: 20,
    district_name_en: 'Nashik',
    district_name_mr: 'नाशिक',
    district_name_hi: 'नासिक',
    sector_id: 1,
    sector_name: 'Automotive Ancillaries',
    job_role_title_en: 'Robotic Welding Automation Operator',
    job_role_title_mr: 'रोबोटिक वेल्डिंग ऑटोमेशन ऑपरेटर',
    job_role_title_hi: 'रोबोटिक वेल्डिंग ऑटोमेशन ऑपरेटर',
    qp_code: 'ASC/Q3103',
    nsqf_level: 4,
    demand_count: 980,
    trained_capacity: 320,
    placement_rate: 76.0,
    gap_score: 77.5,
    severity_level: 'CRITICAL',
    trend_direction: 'RISING',
  },
  {
    id: 'gap-004',
    district_id: 25,
    district_name_en: 'Chh. Sambhajinagar',
    district_name_mr: 'छत्रपती संभाजीनगर',
    district_name_hi: 'छत्रपति संभाजीनगर',
    sector_id: 2,
    sector_name: 'Precision Engineering',
    job_role_title_en: 'Tool & Die Maker (Press Tools)',
    job_role_title_mr: 'टूल अँड डाय मेकर (प्रेस टूल्स)',
    job_role_title_hi: 'टूल एंड डाई मेकर (प्रेस टूल्स)',
    qp_code: 'CSC/Q0302',
    nsqf_level: 5,
    demand_count: 850,
    trained_capacity: 260,
    placement_rate: 80.0,
    gap_score: 79.1,
    severity_level: 'CRITICAL',
    trend_direction: 'RISING',
  },
  {
    id: 'gap-005',
    district_id: 8,
    district_name_en: 'Nagpur',
    district_name_mr: 'नागपूर',
    district_name_hi: 'नागपुर',
    sector_id: 3,
    sector_name: 'Logistics & Aerospace',
    job_role_title_en: 'Aviation Component Assembly Technician',
    job_role_title_mr: 'एव्हिएशन घटक जोडणी तंत्रज्ञ',
    job_role_title_hi: 'विमान घटक असेंबली तकनीशियन',
    qp_code: 'AAS/Q0104',
    nsqf_level: 4,
    demand_count: 740,
    trained_capacity: 220,
    placement_rate: 74.0,
    gap_score: 73.6,
    severity_level: 'HIGH',
    trend_direction: 'RISING',
  },
  {
    id: 'gap-006',
    district_id: 16,
    district_name_en: 'Solapur',
    district_name_mr: 'सोलापूर',
    district_name_hi: 'सोलापुर',
    sector_id: 4,
    sector_name: 'Power & Green Energy',
    job_role_title_en: 'Commercial Solar PV Installation Lead',
    job_role_title_mr: 'व्यावसायिक सोलर पीव्ही इन्स्टॉलेशन प्रमुख',
    job_role_title_hi: 'वाणिज्यिक सोलर पीवी इंस्टॉलेशन लीड',
    qp_code: 'SGJ/Q0101',
    nsqf_level: 4,
    demand_count: 650,
    trained_capacity: 280,
    placement_rate: 71.0,
    gap_score: 68.0,
    severity_level: 'HIGH',
    trend_direction: 'STABLE',
  },
  {
    id: 'gap-007',
    district_id: 17,
    district_name_en: 'Kolhapur',
    district_name_mr: 'कोल्हापूर',
    district_name_hi: 'कोल्हापुर',
    sector_id: 2,
    sector_name: 'Foundry & Heavy Machinery',
    job_role_title_en: 'Induction Furnace Casting Technician',
    job_role_title_mr: 'इंडक्शन फर्नेस कास्टिंग तंत्रज्ञ',
    job_role_title_hi: 'इंडक्शन फर्नेस कास्टिंग तकनीशियन',
    qp_code: 'CSC/Q0204',
    nsqf_level: 3,
    demand_count: 820,
    trained_capacity: 380,
    placement_rate: 75.0,
    gap_score: 70.2,
    severity_level: 'HIGH',
    trend_direction: 'STABLE',
  },
  {
    id: 'gap-008',
    district_id: 14,
    district_name_en: 'Pune',
    district_name_mr: 'पुणे',
    district_name_hi: 'पुणे',
    sector_id: 5,
    sector_name: 'Electronics & Smart Factory',
    job_role_title_en: 'Industrial IoT Sensor Integrator',
    job_role_title_mr: 'औद्योगिक आयओटी सेन्सर इंटिग्रेटर',
    job_role_title_hi: 'औद्योगिक आईओटी सेंसर इंटीग्रेटर',
    qp_code: 'ELE/Q1201',
    nsqf_level: 5,
    demand_count: 1100,
    trained_capacity: 340,
    placement_rate: 81.0,
    gap_score: 78.4,
    severity_level: 'CRITICAL',
    trend_direction: 'RISING',
  },
  {
    id: 'gap-009',
    district_id: 3,
    district_name_en: 'Thane',
    district_name_mr: 'ठाणे',
    district_name_hi: 'ठाणे',
    sector_id: 6,
    sector_name: 'Chemical & Pharmaceuticals',
    job_role_title_en: 'Cleanroom Plant Maintenance Technician',
    job_role_title_mr: 'क्लीनरूम प्लांट देखभाल तंत्रज्ञ',
    job_role_title_hi: 'क्लीनरूम प्लांट रखरखाव तकनीशियन',
    qp_code: 'LFS/Q0205',
    nsqf_level: 4,
    demand_count: 950,
    trained_capacity: 360,
    placement_rate: 76.5,
    gap_score: 74.8,
    severity_level: 'HIGH',
    trend_direction: 'RISING',
  },
  {
    id: 'gap-010',
    district_id: 20,
    district_name_en: 'Nashik',
    district_name_mr: 'नाशिक',
    district_name_hi: 'नासिक',
    sector_id: 7,
    sector_name: 'Agriculture & Food Processing',
    job_role_title_en: 'Cold Storage Refrigeration Specialist',
    job_role_title_mr: 'शीतगृह रेफ्रिजरेशन तज्ज्ञ',
    job_role_title_hi: 'कोल्ड स्टोरेज रेफ्रिजरेशन विशेषज्ञ',
    qp_code: 'FIC/Q0501',
    nsqf_level: 4,
    demand_count: 610,
    trained_capacity: 290,
    placement_rate: 68.0,
    gap_score: 62.4,
    severity_level: 'HIGH',
    trend_direction: 'STABLE',
  },
];

/**
 * Structural Oversupply Alerts (Placement < 25% & Demand < 20th percentile for 2 consecutive quarters)
 */
export const MOCK_OVERSUPPLY_ALERTS: OversupplyAlert[] = [
  {
    id: 'over-001',
    district_name: 'Solapur',
    trade_title: 'Draughtsman (Civil - Manual Drafting)',
    placement_rate: 18.5,
    local_demand_percentile: 12,
    consecutive_quarters: 3,
    intake_capacity: 320,
    recommended_reduction_percent: 50,
  },
  {
    id: 'over-002',
    district_name: 'Dhule',
    trade_title: 'Desk Typewriter & Basic Keypunch',
    placement_rate: 14.0,
    local_demand_percentile: 8,
    consecutive_quarters: 4,
    intake_capacity: 180,
    recommended_reduction_percent: 75,
  },
  {
    id: 'over-003',
    district_name: 'Beed',
    trade_title: 'Manual Sewing Machine Operator (Non-Export)',
    placement_rate: 21.0,
    local_demand_percentile: 16,
    consecutive_quarters: 2,
    intake_capacity: 240,
    recommended_reduction_percent: 40,
  },
];
