# -*- coding: utf-8 -*-
"""
Unifies all 12 diagrams from diagrams_1_to_4, diagrams_5_to_8, and diagrams_9_to_12.
"""
from diagrams_1_to_4 import DIAGRAM_1_CLOSED_LOOP, DIAGRAM_2_C4_SYSTEM, DIAGRAM_3_GAP_ENGINE, DIAGRAM_4_TAXONOMY_FLOW
from diagrams_5_to_8 import DIAGRAM_5_DPDP_PIPELINE, DIAGRAM_6_INGESTION_AIRFLOW, DIAGRAM_7_RAG_PIPELINE, DIAGRAM_8_STRIDE_SECURITY
from diagrams_9_to_12 import DIAGRAM_9_STATE_MACHINE, DIAGRAM_10_ERD, DIAGRAM_11_TESTING_PYRAMID, DIAGRAM_12_CLOUD_TOPOLOGY

__all__ = [
    "DIAGRAM_1_CLOSED_LOOP",
    "DIAGRAM_2_C4_SYSTEM",
    "DIAGRAM_3_GAP_ENGINE",
    "DIAGRAM_4_TAXONOMY_FLOW",
    "DIAGRAM_5_DPDP_PIPELINE",
    "DIAGRAM_6_INGESTION_AIRFLOW",
    "DIAGRAM_7_RAG_PIPELINE",
    "DIAGRAM_8_STRIDE_SECURITY",
    "DIAGRAM_9_STATE_MACHINE",
    "DIAGRAM_10_ERD",
    "DIAGRAM_11_TESTING_PYRAMID",
    "DIAGRAM_12_CLOUD_TOPOLOGY"
]
