/**
 * MahaSkills — Admin Console Synthetic Fixtures
 * Problem Statement ID: 26134
 *
 * Synthetic fixtures for Airflow pipeline ingestion runs, DPDP-compliant
 * audit trail events, and 4-tier hierarchical skill taxonomy tree.
 * In compliance with DPDP Act 2023:
 * Zero raw candidate or user PII. Actor IDs are strictly pseudonymous.
 */

import type { PipelineRun, AuditEvent, TaxonomyNode } from './model';

export const SAMPLE_DATA = true;

export const MOCK_PIPELINE_RUNS: PipelineRun[] = [
  {
    dagId: 'lmi_nightly_job_scraping',
    runId: 'run_lmi_20260818_0200',
    state: 'SUCCESS',
    startedAt: '2026-08-18T02:00:00Z',
    finishedAt: '2026-08-18T02:42:15Z',
    durationSeconds: 2535,
    recordsIn: 54200,
    recordsOut: 48900,
    errorSummary: null,
  },
  {
    dagId: 'lmi_nightly_job_scraping',
    runId: 'run_lmi_20260817_0200',
    state: 'SUCCESS',
    startedAt: '2026-08-17T02:00:00Z',
    finishedAt: '2026-08-17T02:45:10Z',
    durationSeconds: 2710,
    recordsIn: 52100,
    recordsOut: 46800,
    errorSummary: null,
  },
  {
    dagId: 'weekly_gap_score_computation',
    runId: 'run_gap_20260816_0100',
    state: 'SUCCESS',
    startedAt: '2026-08-16T01:00:00Z',
    finishedAt: '2026-08-16T02:18:40Z',
    durationSeconds: 4720,
    recordsIn: 36,
    recordsOut: 36,
    errorSummary: null,
  },
  {
    dagId: 'recommendation_trigger_audit',
    runId: 'run_rec_20260816_0300',
    state: 'SUCCESS',
    startedAt: '2026-08-16T03:00:00Z',
    finishedAt: '2026-08-16T03:22:15Z',
    durationSeconds: 1335,
    recordsIn: 182,
    recordsOut: 14,
    errorSummary: null,
  },
  {
    dagId: 'dag_ncs_sync',
    runId: 'run_ncs_20260818_0330',
    state: 'FAILED',
    startedAt: '2026-08-18T03:30:00Z',
    finishedAt: '2026-08-18T03:35:12Z',
    durationSeconds: 312,
    recordsIn: 12000,
    recordsOut: 0,
    errorSummary: 'NCS Gateway HTTP 504 Gateway Timeout on endpoint /api/v2/vacancies',
  },
  {
    dagId: 'dag_nsdc_taxonomy_sync',
    runId: 'run_nsdc_20260801_0400',
    state: 'SUCCESS',
    startedAt: '2026-08-01T04:00:00Z',
    finishedAt: '2026-08-01T04:58:30Z',
    durationSeconds: 3510,
    recordsIn: 4200,
    recordsOut: 4185,
    errorSummary: null,
  },
];

export const MOCK_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'aud_evt_001',
    actorRole: 'ADMIN',
    actorId: 'usr_ops_8b11',
    action: 'TAXONOMY_SKILL_CREATE',
    resource: 'taxonomy:skills:sk_solid_state_battery',
    scope: 'STATEWIDE',
    timestamp: '2026-08-18T10:15:30Z',
    outcome: 'SUCCESS',
    traceId: '01J9AUDIT001A',
  },
  {
    id: 'aud_evt_002',
    actorRole: 'POLICY_MAKER',
    actorId: 'usr_dseei_4a02',
    action: 'RECOMMENDATION_APPROVE',
    resource: 'recommendations:rec_auto_ev_2026',
    scope: 'STATEWIDE',
    timestamp: '2026-08-18T09:42:10Z',
    outcome: 'SUCCESS',
    traceId: '01J9AUDIT002B',
  },
  {
    id: 'aud_evt_003',
    actorRole: 'DISTRICT_OFFICER',
    actorId: 'usr_dpo_pune_9c71',
    action: 'DISTRICT_PLAN_UPDATE',
    resource: 'district_plans:pune_fy26_27',
    scope: 'DISTRICT:14',
    timestamp: '2026-08-18T08:20:00Z',
    outcome: 'SUCCESS',
    traceId: '01J9AUDIT003C',
  },
  {
    id: 'aud_evt_004',
    actorRole: 'EMPLOYER',
    actorId: 'usr_emp_anon_6e34',
    action: 'SKILL_NEEDS_DECLARE',
    resource: 'skill_needs:sn_pune_ev_001',
    scope: 'DISTRICT:14',
    timestamp: '2026-08-17T15:30:15Z',
    outcome: 'SUCCESS',
    traceId: '01J9AUDIT004D',
  },
  {
    id: 'aud_evt_005',
    actorRole: 'ADMIN',
    actorId: 'usr_ops_8b11',
    action: 'PIPELINE_RETRIGGER',
    resource: 'pipelines:dag_ncs_sync',
    scope: 'SYSTEM',
    timestamp: '2026-08-17T11:05:00Z',
    outcome: 'FAILURE',
    traceId: '01J9AUDIT005E',
  },
  {
    id: 'aud_evt_006',
    actorRole: 'ITI_PRINCIPAL',
    actorId: 'usr_iti_aur_2d18',
    action: 'GLOBAL_CONFIG_MODIFY',
    resource: 'system:settings:retention',
    scope: 'STATEWIDE',
    timestamp: '2026-08-16T14:10:45Z',
    outcome: 'DENIED',
    traceId: '01J9AUDIT006F',
  },
];

export const MOCK_TAXONOMY_TREE: TaxonomyNode[] = [
  {
    id: 'sec_auto',
    code: 'SEC-AUTO',
    nameEn: 'Automotive & Electric Mobility',
    nameMr: 'वाहन आणि इलेक्ट्रिक मोबिलिटी',
    nameHi: 'ऑटोमोटिव और इलेक्ट्रिक मोबिलिटी',
    level: 'sector',
    isEmerging: false,
    children: [
      {
        id: 'ssc_asdc',
        code: 'SSC-ASDC',
        nameEn: 'Automotive Skills Development Council',
        nameMr: 'वाहन कौशल्य विकास परिषद (ASDC)',
        nameHi: 'ऑटोमोटिव कौशल विकास परिषद',
        level: 'ssc',
        parentId: 'sec_auto',
        children: [
          {
            id: 'role_ev_technician',
            code: 'ASC/Q1402',
            nameEn: 'EV Powertrain Assembly Technician',
            nameMr: 'ईव्ही पॉवरट्रेन असेंब्ली तंत्रज्ञ',
            nameHi: 'ईवी पावरट्रेन असेंबली तकनीशियन',
            level: 'job_role',
            parentId: 'ssc_asdc',
            nsqfLevel: 4,
            children: [
              {
                id: 'sk_high_voltage_safety',
                code: 'ELE/N1001',
                nameEn: 'High Voltage Safety & Battery Isolation',
                nameMr: 'हाय व्होल्टेज सुरक्षा आणि बॅटरी आयसोलेशन',
                nameHi: 'उच्च वोल्टेज सुरक्षा और बैटरी अलगाव',
                level: 'skill',
                parentId: 'role_ev_technician',
                isEmerging: false,
              },
              {
                id: 'sk_can_bus_diagnostics',
                code: 'ELE/N1002',
                nameEn: 'CAN Bus & Automotive Diagnostics',
                nameMr: 'कॅन बस आणि वाहन डायग्नोस्टिक्स',
                nameHi: 'कैन बस और ऑटोमोटिव डायग्नोस्टिक्स',
                level: 'skill',
                parentId: 'role_ev_technician',
                isEmerging: false,
              },
              {
                id: 'sk_solid_state_testing',
                code: 'ELE/N1003',
                nameEn: 'Solid State Battery Testing & Analytics',
                nameMr: 'सॉलिड स्टेट बॅटरी चाचणी आणि विश्लेषण',
                nameHi: 'सॉलिड स्टेट बैटरी परीक्षण और एनालिटिक्स',
                level: 'skill',
                parentId: 'role_ev_technician',
                isEmerging: true,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'sec_ites',
    code: 'SEC-ITES',
    nameEn: 'IT & IT-Enabled Services',
    nameMr: 'माहिती तंत्रज्ञान आणि सक्षम सेवा',
    nameHi: 'सूचना प्रौद्योगिकी और सक्षम सेवाएं',
    level: 'sector',
    isEmerging: false,
    children: [
      {
        id: 'ssc_nasscom',
        code: 'SSC-NASSCOM',
        nameEn: 'IT-ITeS Sector Skills Council',
        nameMr: 'आयटी-आयटीईएस कौशल्य परिषद',
        nameHi: 'आईटी-आईटीईएस कौशल परिषद',
        level: 'ssc',
        parentId: 'sec_ites',
        children: [
          {
            id: 'role_fullstack_dev',
            code: 'SSC/Q0501',
            nameEn: 'Full Stack Web Developer',
            nameMr: 'फुल स्टॅक वेब डेव्हलपर',
            nameHi: 'फुल स्टैक वेब डेवलपर',
            level: 'job_role',
            parentId: 'ssc_nasscom',
            nsqfLevel: 5,
            children: [
              {
                id: 'sk_react_typescript',
                code: 'IT/N0101',
                nameEn: 'React TypeScript UI Engineering',
                nameMr: 'रिअॅक्ट टाईपस्क्रिप्ट युआय अभियांत्रिकी',
                nameHi: 'रिएक्ट टाइपस्क्रिप्ट यूआई इंजीनियरिंग',
                level: 'skill',
                parentId: 'role_fullstack_dev',
                isEmerging: false,
              },
              {
                id: 'sk_edge_ai_optimization',
                code: 'IT/N0102',
                nameEn: 'Edge AI On-Device Inference Optimization',
                nameMr: 'एज एआय ऑन-डिव्हाइस इन्फरन्स ऑप्टिमायझेशन',
                nameHi: 'एज एआई ऑन-डिवाइस इन्फरेंस ऑप्टिमाइज़ेशन',
                level: 'skill',
                parentId: 'role_fullstack_dev',
                isEmerging: true,
              },
            ],
          },
        ],
      },
    ],
  },
];
