import { DistrictPlan } from './model';

export const SAMPLE_DATA = true;

export const MOCK_DISTRICT_PLANS: DistrictPlan[] = [
  {
    id: 'dp-pune-2026-27',
    districtId: 2712,
    districtName: 'Pune',
    fiscalYear: '2026-27',
    version: 1,
    status: 'DRAFT',
    planType: 'ANNUAL',
    currentStage: 'ITI_CAPACITY',
    intakeTargets: [
      {
        courseCode: 'CRS-ELEC-01',
        courseTitle: 'Electrician (EV Specialization)',
        currentSeats: 80,
        proposedSeats: 100,
        demandBasis: 'High industrial EV cluster demand in Chakan & Talegaon auto belts',
      },
      {
        courseCode: 'CRS-FITTER-02',
        courseTitle: 'Fitter Assembly Specialist',
        currentSeats: 120,
        proposedSeats: 120,
        demandBasis: 'Consistent mechanical component fabrication requirements across Bhosari',
      },
      {
        courseCode: 'CRS-SOLAR-03',
        courseTitle: 'Solar PV Installation & Maintenance Technician',
        currentSeats: 40,
        proposedSeats: 70,
        demandBasis: 'Maharashtra Clean Energy Policy rooftop solar mandate for commercial sheds',
        justification:
          'Expanded intake justified by 3 new solar manufacturing facilities in Shirur corridor',
      },
      {
        courseCode: 'CRS-CNC-04',
        courseTitle: 'CNC Operator & Programmer',
        currentSeats: 60,
        proposedSeats: 60,
        demandBasis: 'Steady automotive die-casting and precision engineering demand',
      },
    ],
    equipmentDeficits: [
      {
        id: 'eq-pun-01',
        itiId: 'ITI-PUN-01',
        itiName: 'Government ITI Aundh',
        item: 'CNC Lathe Tooling Station',
        qty: 2,
        unitCostInr: 450000,
      },
      {
        id: 'eq-pun-02',
        itiId: 'ITI-PUN-01',
        itiName: 'Government ITI Aundh',
        item: 'Solar Inverter Diagnostic Kit',
        qty: 4,
        unitCostInr: 85000,
      },
      {
        id: 'eq-pun-03',
        itiId: 'ITI-PUN-02',
        itiName: 'Government ITI Haveli',
        item: 'Industrial IoT Sensor Demo Bench',
        qty: 1,
        unitCostInr: 320000,
      },
    ],
    trainerUpskilling: [
      {
        id: 'tu-pun-01',
        trade: 'Solar PV Installation & Maintenance',
        count: 4,
      },
      {
        id: 'tu-pun-02',
        trade: 'Electrician (EV Specialization)',
        count: 6,
      },
    ],
    budgetFactors: [
      {
        factor: 'DEMAND',
        labelKey: 'plans:budget.factors.demand',
        rawValue: 88,
        weight: 0.4,
        contribution: 35.2,
      },
      {
        factor: 'CURRENT_CAPACITY',
        labelKey: 'plans:budget.factors.capacity',
        rawValue: 72,
        weight: 0.3,
        contribution: 21.6,
      },
      {
        factor: 'HISTORICAL_PLACEMENT',
        labelKey: 'plans:budget.factors.placement',
        rawValue: 80,
        weight: 0.3,
        contribution: 24.0,
      },
    ],
    totalTargetIntake: 350,
    totalEstimatedBudget: 1560000,
    createdAt: '2026-09-01T08:00:00.000Z',
    updatedAt: '2026-09-16T14:20:00.000Z',
    updatedBy: 'user-do-pune-01',
  },
  {
    id: 'dp-nagpur-2026-27',
    districtId: 2709,
    districtName: 'Nagpur',
    fiscalYear: '2026-27',
    version: 3,
    status: 'SUBMITTED',
    planType: 'ANNUAL',
    currentStage: 'SUBMISSION',
    intakeTargets: [
      {
        courseCode: 'CRS-WELD-01',
        courseTitle: 'Multi-Process Welder (TIG/MIG)',
        currentSeats: 100,
        proposedSeats: 120,
        demandBasis: 'MIHAN Multi-Modal International Cargo Hub and Airport expansion',
      },
      {
        courseCode: 'CRS-ELEC-01',
        courseTitle: 'Industrial Electrician',
        currentSeats: 90,
        proposedSeats: 110,
        demandBasis: 'Regional power transmission grid substation modernization',
      },
      {
        courseCode: 'CRS-MECH-02',
        courseTitle: 'Mechatronics Automation Associate',
        currentSeats: 30,
        proposedSeats: 50,
        demandBasis: 'Aerospace manufacturing supplier base inside Butibori MIDC',
        justification:
          'Defense corridor expansion requires specialized mechatronics technicians with PLC competence',
      },
    ],
    equipmentDeficits: [
      {
        id: 'eq-nag-01',
        itiId: 'ITI-NAG-01',
        itiName: 'Government ITI Nagpur City',
        item: 'TIG/MIG Multi-Process Welding Booth',
        qty: 3,
        unitCostInr: 280000,
      },
      {
        id: 'eq-nag-02',
        itiId: 'ITI-NAG-02',
        itiName: 'Government ITI Butibori',
        item: 'Programmable Logic Controller (PLC) Trainer',
        qty: 2,
        unitCostInr: 390000,
      },
    ],
    trainerUpskilling: [
      {
        id: 'tu-nag-01',
        trade: 'Mechatronics Automation Associate',
        count: 3,
      },
      {
        id: 'tu-nag-02',
        trade: 'Multi-Process Welder',
        count: 5,
      },
    ],
    budgetFactors: [
      {
        factor: 'DEMAND',
        labelKey: 'plans:budget.factors.demand',
        rawValue: 78,
        weight: 0.4,
        contribution: 31.2,
      },
      {
        factor: 'CURRENT_CAPACITY',
        labelKey: 'plans:budget.factors.capacity',
        rawValue: 65,
        weight: 0.3,
        contribution: 19.5,
      },
      {
        factor: 'HISTORICAL_PLACEMENT',
        labelKey: 'plans:budget.factors.placement',
        rawValue: 75,
        weight: 0.3,
        contribution: 22.5,
      },
    ],
    totalTargetIntake: 280,
    totalEstimatedBudget: 1620000,
    submittedAt: '2026-09-15T10:30:00.000Z',
    submittedBy: 'user-do-nagpur-01',
    createdAt: '2026-09-02T09:00:00.000Z',
    updatedAt: '2026-09-15T10:30:00.000Z',
    updatedBy: 'user-do-nagpur-01',
  },
  {
    id: 'dp-nashik-2026-27',
    districtId: 2720,
    districtName: 'Nashik',
    fiscalYear: '2026-27',
    version: 5,
    status: 'PUBLISHED',
    planType: 'ANNUAL',
    currentStage: 'SUBMISSION',
    intakeTargets: [
      {
        courseCode: 'CRS-FOOD-01',
        courseTitle: 'Food Processing & Quality Technician',
        currentSeats: 60,
        proposedSeats: 80,
        demandBasis: 'Dindori and Niphad wine and agricultural processing export zone',
      },
      {
        courseCode: 'CRS-ELEC-05',
        courseTitle: 'Electronic Mechanic (Avionics Support)',
        currentSeats: 80,
        proposedSeats: 80,
        demandBasis: 'HAL Ozar defense aeronautics ancillary cluster maintenance demand',
      },
      {
        courseCode: 'CRS-MACH-02',
        courseTitle: 'Machinist Precision Toolmaker',
        currentSeats: 70,
        proposedSeats: 70,
        demandBasis: 'Satpur and Ambad engineering SME tooling replacement cycle',
      },
    ],
    equipmentDeficits: [
      {
        id: 'eq-nsk-01',
        itiId: 'ITI-NSK-01',
        itiName: 'Government ITI Nashik',
        item: 'Food Quality Testing Spectrophotometer',
        qty: 1,
        unitCostInr: 520000,
      },
      {
        id: 'eq-nsk-02',
        itiId: 'ITI-NSK-02',
        itiName: 'Government ITI Sinnar',
        item: 'Precision Surface Grinder',
        qty: 1,
        unitCostInr: 340000,
      },
    ],
    trainerUpskilling: [
      {
        id: 'tu-nsk-01',
        trade: 'Food Processing & Quality',
        count: 2,
      },
      {
        id: 'tu-nsk-02',
        trade: 'Machinist Precision Toolmaker',
        count: 4,
      },
    ],
    budgetFactors: [
      {
        factor: 'DEMAND',
        labelKey: 'plans:budget.factors.demand',
        rawValue: 82,
        weight: 0.4,
        contribution: 32.8,
      },
      {
        factor: 'CURRENT_CAPACITY',
        labelKey: 'plans:budget.factors.capacity',
        rawValue: 80,
        weight: 0.3,
        contribution: 24.0,
      },
      {
        factor: 'HISTORICAL_PLACEMENT',
        labelKey: 'plans:budget.factors.placement',
        rawValue: 85,
        weight: 0.3,
        contribution: 25.5,
      },
    ],
    totalTargetIntake: 230,
    totalEstimatedBudget: 860000,
    submittedAt: '2026-09-08T11:15:00.000Z',
    submittedBy: 'user-do-nashik-01',
    publishedAt: '2026-09-10T14:00:00.000Z',
    publishedBy: 'user-pm-dseei-01',
    createdAt: '2026-08-25T07:30:00.000Z',
    updatedAt: '2026-09-10T14:00:00.000Z',
    updatedBy: 'user-pm-dseei-01',
  },
];
